name: Flutter CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:" # optional, change this to force refresh cache
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:" # optional, change this to specify the cache path
          pub-cache-key: "flutter-pub:os:-:channel:-:version:-:arch:-:hash:" # optional, change this to force refresh cache of dart pub get dependencies
          pub-cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:" # optional, change this to specify the cache path

      - run: flutter --version
      - run: flutter pub get
      - run: flutter build apk

      # - name: Extract version from pubspec.yaml
      #   id: extract_version
      #   run: |
      #     VERSION=$(sed -n 's/^version: //p' pubspec.yaml)
      #     echo "VERSION=$VERSION" >> $GITHUB_ENV

      # - name: Create GitHub Release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.TOKEN }}
      #   run: |
      #     gh release create $VERSION \
      #     --title "Release $VERSION" \
      #     --notes "Release notes for version $VERSION" \
      #     build/app/outputs/apk/release/*

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: build${{ env.VERSION }}
          token: ${{ secrets.TOKEN }}
          
